### ISSUE TITLE
cron not starting

### ISSUE THREAD

**Issue by sandeep318** [ulsmith/alpine-apache-php7#5]
Hi,

I have been using this docker image for my php  applications.  I noticed crond is not starting by default. I have added  "CMD ["crond", "-f"]"  and it is running as a demon (along with /bin/sh /bootstrap/start.sh )  but the cron is not running. 

+++
 1     0 root     S     1584   0%   1   0% {start.sh} /bin/sh /bootstrap/start.sh crond -f
++

when I manually run "crond" in the docker container. it is working 

any idea how can I achieve this? 

My Dockerfile

++
FROM ulsmith/alpine-apache-php7
WORKDIR /app/public
COPY .  .
COPY vhost.conf  /etc/apache2/conf.d/
RUN composer install -d /app/public/
RUN chown -R apache. /app/
RUN /usr/bin/crontab crontab.txt
CMD ["crond", "-f"]
EXPOSE 80

**Comment by smiffy6969** [comment]
One process per docker container. 

If you want to run Cron, run it in another container and his this container from that one.

It is possible to run multiple processes in a docker container but it's not really what it's supposed to be doing.

What are you trying to run? Is it some kind of PHP stack that also has timed background services? If it is and you want to run in docker I would use their API endpoints and hit them from another container running Cron via local address.

Paul


---- On Fri, 01 Mar 2019 07:21:42 +0000 notifications@github.com wrote ----



Hi,

I have been using this docker image for my php applications. I noticed crond is not starting by default. I have added "CMD ["crond", "-f"]" and it is running as a demon (along with /bin/sh /bootstrap/start.sh ) but the cron is not running.

+++
1 0 root S 1584 0% 1 0% {start.sh} /bin/sh /bootstrap/start.sh crond -f
++

when I manually run "crond" in the docker container. it is working

any idea how can I achieve this?

My Dockerfile

++
FROM ulsmith/alpine-apache-php7
WORKDIR /app/public
COPY . .
COPY vhost.conf /etc/apache2/conf.d/
RUN composer install -d /app/public/
RUN chown -R apache. /app/
RUN /usr/bin/crontab crontab.txt
CMD ["crond", "-f"]
EXPOSE 80

**Comment by sandeep318** [comment]
Thanks Paul for your fast reply. I am a newbie into this. 

I am running few apis with this docker image. one of the api need a rabbit MQ listening and it is started by the below command  (it will start the listener if it is not running. )

++
php /app/public/yii  cron/start-queue-listener
++

Is there any chance that we can execute this command when the container is started or set as a cron job so that it will start it. I am using  aws ecr and aws ecs to deploy it.

**Comment by smiffy6969** [comment]
Hmmmmm ok, no problem we are all learning all the time.

First things first, docker is not a virtual machine. Its a case of using the right tool for the job. If you have several APIs then you need to orchastrate this in docker. Each API on its own container all talking over IP. Personally I would use a traefik load balancer, buy a virtual machine and run several containers each running game single process all talking to each other, one would be a Cron.

Docker containers are sandboxes singular processes although you can run multiple you don't want to, trust me.

You need to do some research on docker and how it fits in to application architecture, I would suggest you read some examples on docker use cases.

You could happily use docker images in AWS and orchestrate them to talk to each other too, if you don't fancy running a VPS, there are many choices, but I thing you need to get some advice on architecture as your trying to do too much in a single container.

Stick to the golden rule of one process per container. Do not run the Cron from the same container, you can but you don't want to really.

If you do still want to do this, extend my image and go from there. Use your own build file..... Or just bash into the running container and start it manually.

docker exec -it (container id) bash

Then you can manually do what you like. You will need to do this each time you start stop it.

Paul


---- On Fri, 01 Mar 2019 07:53:50 +0000 notifications@github.com wrote ----



Thanks Paul for your fast reply. I am a newbie into this.

I am running few apis with this docker image. one of the api need a rabbit MQ listening and it is started by the below command (it will start the listener if it is not running. )

++
php /app/public/yii cron/start-queue-listener
++

Is there any chance that we can execute this command when the container is started or set as a cron job so that it will start it. I am using aws ecr and aws ecs to deploy it.

**Comment by sandeep318** [comment]
Thanks paul for your time. I will  talk with the developers and make it as a separate service. This will make it simple.
